### ISSUE TITLE
unable to join room in swift UI

### ISSUE THREAD

**Issue by phng0926** [daily-co/daily-client-ios#10] opened 2024-08-05 16:51 UTC
every time the app joins a room, it will join successfully for once and failed quickly ( join for a 2nd time? ). In my code, i only joined once. 

my code:
```
    private var defaultSettings = ClientSettingsUpdate(inputs: .set(.init(camera: .set(.enabled(false)))))

    
    @MainActor func manualJoin(room_url_string: String) {
        if callClient.callState == .joined || callClient.callState == .joining {
            return
        }
        print("Joining room...")
        guard let roomURL = URL(string: room_url_string) else {
            return
        }
        // Join with custom camera settings
            callClient.join(url: roomURL, settings: defaultSettings ) { result in
            print(result)
            // You can either handle the join event in a callback or in a delegate method.
        }
    }
```

here is the log from the console. 

> success(Daily.CallJoinData(participants: Daily.Participants(local: Daily.Participant(id: 521748ec-4446-4d8e-954c-0f376baad7ec, info: Daily.ParticipantInfo(isLocal: true, isOwner: false, joinedAt: Optional(2024-08-05 16:28:05 +0000), userID: nil, username: nil, permissions: Optional(Daily.ParticipantPermissions(hasPresence: true, canSend: Set([Daily.CanSendPermission.customVideo, Daily.CanSendPermission.screenVideo, Daily.CanSendPermission.camera, Daily.CanSendPermission.customAudio, Daily.CanSendPermission.microphone, Daily.CanSendPermission.screenAudio]), canAdmin: Set([])))), media: Optional(Daily.ParticipantMedia(camera: Daily.ParticipantVideoInfo(state: Daily.MediaState.off(reasons: Set([Daily.MediaOffReason.user])), subscribed: Daily.TrackSubscriptionState.unsubscribed, trackID: nil), microphone: Daily.ParticipantAudioInfo(state: Daily.MediaState.playable, subscribed: Daily.TrackSubscriptionState.unsubscribed, trackID: Optional(Daily.MediaStreamTrackID(stringValue: "1DFC7094-A35B-41FB-8859-76FEC0BEAFB1"))), screenVideo: Daily.ParticipantVideoInfo(state: Daily.MediaState.off(reasons: Set([Daily.MediaOffReason.user])), subscribed: Daily.TrackSubscriptionState.unsubscribed, trackID: nil), screenAudio: Daily.ParticipantAudioInfo(state: Daily.MediaState.off(reasons: Set([Daily.MediaOffReason.user])), subscribed: Daily.TrackSubscriptionState.unsubscribed, trackID: nil), customAudio: [:], customVideo: [:]))), remote: [:]), meetingSession: Daily.MeetingSession(id: 1a1da347-ecaa-4b80-a77e-07e843705f48)))
> failure(Daily.CallClientError.core(Daily.CoreCallClientError.request(Daily.RequestError(message: Optional("Connection(CallState(AlreadyInCall))")))))

**Comment by filipi87** [comment] 2024-08-22 18:24
Hi @phng0926,

Thanks for reporting this.

Looking at the logs, it seems that you are already in the call, and that is why the system it is throwing this exception:
```
failure(Daily.CallClientError.core(Daily.CoreCallClientError.request(Daily.RequestError(message: Optional("Connection(CallState(AlreadyInCall))")))))
```

Are you able to reproduce it using one of our demos ? 
- https://github.com/daily-demos/daily-ios-demo
- https://github.com/daily-demos/daily-ios-starter-kit (developed with SwiftUI). I was unable to reproduce the issue with this demo.

If you continue to experience this issue, please provide:
- A complete code snippet to help us replicate the issue.
- The full log.
- The version of our SDK you are using and the device on which you’re testing.

This information will help us assist you more effectively.

**Comment by filipi87** [comment] 2024-10-15 16:06
Hi, considering that the inactity, and based on our investigations, it appears that everything is working as expected.

As such, we’re closing this issue for now. However, if the problem persists or you have any new information to provide, please feel free to open a new issue and share the details. We’ll be happy to take another look.

**Closed by filipi87** 2024-10-15 16:06 UTC
